### ISSUE TITLE
Schema validation

### ISSUE THREAD

**Issue by orochies** [infinispan/infinispan-cachestore-mongodb#13]
Because the xml editor launches validation error:
- Cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element mongodbStore

In the line of code:
`
<mongodbStore xmlns="urn:Infinispan:config:mongodb:8.2">`

How can i solve this?

**Comment by galderz** [comment]
Hmmm, can you show the entire XML file? Maybe you're missing mongo schema URL link?

**Comment by orochies** [comment]
The code is as follows thanks:

```
<?xml version="1.0" encoding="UTF-8"?>
<infinispan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:infinispan:config:8.2 http://www.infinispan.org/schemas/infinispan-config-8.2.xsd"
	xmlns="urn:infinispan:config:8.2">

	<cache-container default-cache="default" statistics="false">

		<local-cache-configuration name="photos-config">
			<eviction size="1000" />
			<persistence>
				<mongodbStore xmlns="urn:infinispan:config:mongodb:8.2">
					<connection collection="photos"
						uri="mongodb://localhost:27017/withis_cachestore?w=0&amp;connectTimeoutMS=2000" />
				</mongodbStore>
			</persistence>
		</local-cache-configuration>
		
		<local-cache-configuration name="entries-config">
			<eviction size="1000" />
			<persistence>
				<mongodbStore xmlns="urn:infinispan:config:mongodb:8.2">
					<connection collection="entries"
						uri="mongodb://localhost:27017/withis_cachestore?w=0&amp;connectTimeoutMS=2000" />
				</mongodbStore>
			</persistence>
		</local-cache-configuration>

		<local-cache name="thumbs" configuration="photos-config">

		</local-cache>

		<local-cache name="medium-photo" configuration="photos-config">

		</local-cache>

		<local-cache name="localities" configuration="entries-config">

		</local-cache>

	</cache-container>

</infinispan>
```

**Comment by galderz** [comment]
http://www.infinispan.org/schemas/infinispan-config-8.2.xsd does not include the mongodbStore store definition. That's in a separate schema file. I don't think we currently have any mongo db store schemas published but you can figure out which mongodb store version you are using, download its schema (e.g. for master this is located [here](https://github.com/infinispan/infinispan-cachestore-mongodb/blob/master/src/main/resources/schemas/mongodb-cachestore-config-8.2.xsd)) and reference it.

**Comment by tristantarrant** [comment]
Hi, I've just issued a PR which fixes the schema among other things. See 
https://github.com/tristantarrant/infinispan-cachestore-mongodb/blob/827c3af3effd2477154b9e096338f4a6f90bde94/src/test/resources/config/mongodb-config.xml
Once that is merged, I can release a new version of the cachestore and publish the schema at the appropriate coordinates.
