### ISSUE TITLE
Async or write-behind is not working.

### ISSUE THREAD

**Issue by xenthik** [infinispan/infinispan-cachestore-mongodb#14]
There is no way to enable Aync mode/write-behind through API or XML configuration.  is infinispan-cachestore-mongodb doen't support.

**Comment by tristantarrant** [comment]
https://issues.jboss.org/browse/ISPN-6715 and https://github.com/infinispan/infinispan-cachestore-mongodb/pull/15

**Comment by xenthik** [comment]
One thing i am trying to figure out the difference in putAsync and org.infinispan.configuration.cache.AsyncStoreConfiguration, even if it always shows AsyncStoreConfiguration.ENABLED is false. But putAsync is works like write-behind. is there any relationship between putAsync and  AsyncStoreConfiguration ?

**Comment by tristantarrant** [comment]
cache.putAsync() will asynchronously put the entry into the cache. The following should help you understand:
put() to a persistent write-through cache (i.e. write-behind disabled): writes to both memory and to the cache store before returning
put() to a persistent write-behind cache: writes to memory and returns. Writing to the cache store is performed asynchronously on a separate thread.
putAsync() to a persistent write-through cache (i.e. write-behind disabled): returns immediately. Writes to both memory and to the cache store happen on a single separate thread.
putAsync() to a persistent write-behind cache: returns immediately.  Writes to memory and to the cache store is performed asynchronously on two separate threads.

**Comment by xenthik** [comment]
How can i enable(use) write-behind through API ? my configurations looks like following? 

   AsyncStoreConfiguration asyncStore = 
	    		 p.addStore(MongoDBStoreConfigurationBuilder.class).ignoreModifications(false)
		    .purgeOnStartup(false)
		    .fetchPersistentState(true)
		    .preload(true)
		    .connectionURI("mongodb://" + hostname + ":" + port + "/" + DATABASE + "?connectTimeoutMS=1000&w=1")
	        .collection(COLLECTION)
	        .create()
	     	.async();
	     System.out.println(asyncStore.enabled()); // this gives false.
	     config = b.build();

**Comment by tristantarrant** [comment]
See https://github.com/infinispan/infinispan-cachestore-mongodb/blob/master/src/test/java/org/infinispan/persistence/mongodb/configuration/MongoDBStoreConfigurationBuilderTest.java#L28

**Comment by galderz** [comment]
This is now fixed, closing.

**Comment by xenthik** [comment]
Configuration conf = builder
              .persistence()
              .addStore(MongoDBStoreConfigurationBuilder.class)
              .connectionURI(CONNECTION_URI)
              .collection(COLLECTION)
              .async().enable()
              .build();

In MongoDBStoreConfigurationBuilderTest.java, follwoing test is getting failed , Why ? assertTrue(conf.persistence().fetchPersistentState());

**Comment by xenthik** [comment]
Even if i have following configuration xml, 

 <persistence passivation="false">
                <mongodbStore xmlns="urn:infinispan:config:store:mongodb:8.2" shared="true" preload="true" fetch-state="true" purge="false" singleton="true">
                    <connection
                            uri="mongodb://mongoUser:mongoPass@localhost:27017/infinispan_test_database?w=0&amp;connectTimeoutMS=2000"
                            collection="infinispan_cachestore"/>
                     <write-behind />                 
                </mongodbStore>                
            </persistence>

it shows,

[AbstractStoreConfiguration [attributes=[**_shared=false, ignoreModifications=false, fetchPersistentState=false, purgeOnStartup=false, preload=false_**, properties={}], async=AsyncStoreConfiguration [attributes=[enabled=false, modificationQueueSize=1024, threadPoolSize=1]], singletonStore=SingletonStoreConfiguration [attributes=[pushStateWhenCoordinator=true, pushStateTimeout=10000, enabled=false]]]]

**Comment by xenthik** [comment]
Even if I have following configurations  ` <persistence passivation="false">
                <mongodbStore xmlns="urn:infinispan:config:store:mongodb:8.2" shared="true" preload="true" fetch-state="true" purge="false" singleton="true">
                    <connection
                            uri="mongodb://mongoUser:mongoPass@localhost:27017/infinispan_test_database?w=0&amp;connectTimeoutMS=2000"
                            collection="infinispan_cachestore"/>
                     <write-behind />                 
                </mongodbStore>
                
            </persistence>`

List<StoreConfiguration> stores give the following output against the configuration:
[AbstractStoreConfiguration [attributes=[**_shared=false, ignoreModifications=false, fetchPersistentState=false, purgeOnStartup=false, preload=false_**, properties={}], async=AsyncStoreConfiguration [attributes=[enabled=false, modificationQueueSize=1024, threadPoolSize=1]], singletonStore=SingletonStoreConfiguration [attributes=[pushStateWhenCoordinator=true, pushStateTimeout=10000, enabled=false]]]]

**Comment by tristantarrant** [comment]
Running mvn clean install from master
Results :
Tests run: 14, Failures: 0, Errors: 0, Skipped: 0

How are you running it ?
I plan to do a release this week.
