### ISSUE TITLE
Push to maven central

### ISSUE THREAD

**Issue by yarpior** [infinispan/infinispan-cachestore-mongodb#18]
Hi. There is a problem with integration 8.2.1 version with infinispan 9.x, so I wonder if you can upload latest version in maven central

**Comment by galderz** [comment]
What's the problem exactly?

**Comment by yarpior** [comment]
NoSuchMethodError: org.infinispan.persistence.spi.InitializationContext.getTimeService()

**Comment by tristantarrant** [comment]
I'll handle that

**Comment by tristantarrant** [comment]
Pushed to JBoss Nexus. It will sync soon.
