### ISSUE TITLE
Extension status

### ISSUE THREAD

**Issue by antoniomacri** [infinispan/infinispan-cachestore-mongodb#21]
I have errors when using the extension with newer Infinispan versions (I'm interested in v14 but also have errors with v11).

It's unfortunate that this extension is unmaintained.

Is there interest in updating it?

I could help with this but I am quite new to Infinispan so I may need some guidance.

**Comment by tristantarrant** [comment]
Ciao Antonio,
we will certainly help you in reviving this store. There are different levels of "upgrade":

* modify the store to the new SPI, maintaining the legacy sync mongodb driver
* replace the legacy sync mongodb driver with the reactive one, tying in with Infinispan's reactive store SPI (optional, but preferred)
* implement mapping of mongodb documents to cache entries (protobuf, json, ...) (optional)

**Comment by tristantarrant** [comment]
> What do you mean with the third point?

The current mongodb cache store stores entries as "blobs". It would be great if it could actually map them to structured documents
